config/routes.rb
Rails.application.routes.draw do
  
  root 'newsletters#index'

  get  'newsletters/new'

  resources :pta_happenings

  resources :upcoming_events

  resources :shoutouts

  resources :newsletters

  resources :users

end

app/models/pta_happening.rb
class PtaHappening < ActiveRecord::Base

 	belongs_to :user

end

app/controllers/pta_happenings_controller.rb
class PtaHappeningsController < ApplicationController
  before_action :set_pta_happening, only: [:show, :edit, :update, :destroy]

  # GET /pta_happenings
  # GET /pta_happenings.json
  def index
    @pta_happenings = PtaHappening.all
  end

  # GET /pta_happenings/1
  # GET /pta_happenings/1.json
  def show
  end

  # GET /pta_happenings/new
  def new
    @pta_happening = PtaHappening.new
  end

  # GET /pta_happenings/1/edit
  def edit
  end

  # POST /pta_happenings
  # POST /pta_happenings.json
  def create
    @pta_happening = PtaHappening.new(pta_happening_params)

    respond_to do |format|
      if @pta_happening.save
        format.html { redirect_to @pta_happening, notice: 'Pta happening was successfully created.' }
        format.json { render :show, status: :created, location: @pta_happening }
      else
        format.html { render :new }
        format.json { render json: @pta_happening.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pta_happenings/1
  # PATCH/PUT /pta_happenings/1.json
  def update
    respond_to do |format|
      if @pta_happening.update(pta_happening_params)
        format.html { redirect_to @pta_happening, notice: 'Pta happening was successfully updated.' }
        format.json { render :show, status: :ok, location: @pta_happening }
      else
        format.html { render :edit }
        format.json { render json: @pta_happening.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pta_happenings/1
  # DELETE /pta_happenings/1.json
  def destroy
    @pta_happening.destroy
    respond_to do |format|
      format.html { redirect_to pta_happenings_url, notice: 'Pta happening was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pta_happening
      @pta_happening = PtaHappening.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pta_happening_params
      params.require(:pta_happening).permit(:name, :content, :newsletter_id)
    end
end

app/helpers/pta_happenings_helper.rb
module PtaHappeningsHelper
end

app/views/pta_happenings/_form.html.erb
<%= form_for(@pta_happening) do |f| %>
  <% if @pta_happening.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pta_happening.errors.count, "error") %> prohibited this pta_happening from being saved:</h2>

      <ul>
      <% @pta_happening.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :newsletter_id %><br>
    <%= f.number_field :newsletter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pta_happenings/edit.html.erb
<h1>Editing pta_happening</h1>

<%= render 'form' %>

<%= link_to 'Show', @pta_happening %> |
<%= link_to 'Back', pta_happenings_path %>

app/views/pta_happenings/index.html.erb
<h1>Listing pta_happenings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Newsletter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pta_happenings.each do |pta_happening| %>
      <tr>
        <td><%= pta_happening.name %></td>
        <td><%= pta_happening.content %></td>
        <td><%= pta_happening.newsletter_id %></td>
        <td><%= link_to 'Show', pta_happening %></td>
        <td><%= link_to 'Edit', edit_pta_happening_path(pta_happening) %></td>
        <td><%= link_to 'Destroy', pta_happening, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pta happening', new_pta_happening_path %>

app/views/pta_happenings/new.html.erb
<h1>New pta_happening</h1>

<%= render 'form' %>

<%= link_to 'Back', pta_happenings_path %>

app/views/pta_happenings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pta_happening.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @pta_happening.content %>
</p>

<p>
  <strong>Newsletter:</strong>
  <%= @pta_happening.newsletter_id %>
</p>

<%= link_to 'Edit', edit_pta_happening_path(@pta_happening) %> |
<%= link_to 'Back', pta_happenings_path %>