config/routes.rb
Rails.application.routes.draw do
  
  root 'newsletters#index'

  get  'newsletters/new'

  resources :pta_happenings

  resources :upcoming_events

  resources :shoutouts

  resources :newsletters

  resources :users

end

app/models/shoutout.rb
class Shoutout < ActiveRecord::Base

 	belongs_to :user

end

app/controllers/shoutouts_controller.rb
class ShoutoutsController < ApplicationController
  before_action :set_shoutout, only: [:show, :edit, :update, :destroy]

  # GET /shoutouts
  # GET /shoutouts.json
  def index
    @shoutouts = Shoutout.all
  end

  # GET /shoutouts/1
  # GET /shoutouts/1.json
  def show
  end

  # GET /shoutouts/new
  def new
    @shoutout = Shoutout.new
  end

  # GET /shoutouts/1/edit
  def edit
  end

  # POST /shoutouts
  # POST /shoutouts.json
  def create
    @shoutout = Shoutout.new(shoutout_params)

    respond_to do |format|
      if @shoutout.save
        format.html { redirect_to @shoutout, notice: 'Shoutout was successfully created.' }
        format.json { render :show, status: :created, location: @shoutout }
      else
        format.html { render :new }
        format.json { render json: @shoutout.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shoutouts/1
  # PATCH/PUT /shoutouts/1.json
  def update
    respond_to do |format|
      if @shoutout.update(shoutout_params)
        format.html { redirect_to @shoutout, notice: 'Shoutout was successfully updated.' }
        format.json { render :show, status: :ok, location: @shoutout }
      else
        format.html { render :edit }
        format.json { render json: @shoutout.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoutouts/1
  # DELETE /shoutouts/1.json
  def destroy
    @shoutout.destroy
    respond_to do |format|
      format.html { redirect_to shoutouts_url, notice: 'Shoutout was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoutout
      @shoutout = Shoutout.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoutout_params
      params.require(:shoutout).permit(:name, :content, :newsletter_id)
    end
end

app/helpers/shoutouts_helper.rb
module ShoutoutsHelper
end

app/views/shoutouts/_form.html.erb
<%= form_for(@shoutout) do |f| %>
  <% if @shoutout.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shoutout.errors.count, "error") %> prohibited this shoutout from being saved:</h2>

      <ul>
      <% @shoutout.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :newsletter_id %><br>
    <%= f.number_field :newsletter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shoutouts/edit.html.erb
<h1>Editing shoutout</h1>

<%= render 'form' %>

<%= link_to 'Show', @shoutout %> |
<%= link_to 'Back', shoutouts_path %>

app/views/shoutouts/index.html.erb
<h1>Listing shoutouts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Newsletter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoutouts.each do |shoutout| %>
      <tr>
        <td><%= shoutout.name %></td>
        <td><%= shoutout.content %></td>
        <td><%= shoutout.newsletter_id %></td>
        <td><%= link_to 'Show', shoutout %></td>
        <td><%= link_to 'Edit', edit_shoutout_path(shoutout) %></td>
        <td><%= link_to 'Destroy', shoutout, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoutout', new_shoutout_path %>

app/views/shoutouts/new.html.erb
<h1>New shoutout</h1>

<%= render 'form' %>

<%= link_to 'Back', shoutouts_path %>

app/views/shoutouts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shoutout.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @shoutout.content %>
</p>

<p>
  <strong>Newsletter:</strong>
  <%= @shoutout.newsletter_id %>
</p>

<%= link_to 'Edit', edit_shoutout_path(@shoutout) %> |
<%= link_to 'Back', shoutouts_path %>