config/routes.rb
Rails.application.routes.draw do
  
  root 'newsletters#index'

  get  'newsletters/new'

  resources :pta_happenings

  resources :upcoming_events

  resources :shoutouts

  resources :newsletters

  resources :users

end

app/models/upcoming_event.rb
class UpcomingEvent < ActiveRecord::Base

	 belongs_to :user

end

app/controllers/upcoming_events_controller.rb
class UpcomingEventsController < ApplicationController
  before_action :set_upcoming_event, only: [:show, :edit, :update, :destroy]

  # GET /upcoming_events
  # GET /upcoming_events.json
  def index
    @upcoming_events = UpcomingEvent.all
  end

  # GET /upcoming_events/1
  # GET /upcoming_events/1.json
  def show
  end

  # GET /upcoming_events/new
  def new
    @upcoming_event = UpcomingEvent.new
  end

  # GET /upcoming_events/1/edit
  def edit
  end

  # POST /upcoming_events
  # POST /upcoming_events.json
  def create
    @upcoming_event = UpcomingEvent.new(upcoming_event_params)

    respond_to do |format|
      if @upcoming_event.save
        format.html { redirect_to @upcoming_event, notice: 'Upcoming event was successfully created.' }
        format.json { render :show, status: :created, location: @upcoming_event }
      else
        format.html { render :new }
        format.json { render json: @upcoming_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /upcoming_events/1
  # PATCH/PUT /upcoming_events/1.json
  def update
    respond_to do |format|
      if @upcoming_event.update(upcoming_event_params)
        format.html { redirect_to @upcoming_event, notice: 'Upcoming event was successfully updated.' }
        format.json { render :show, status: :ok, location: @upcoming_event }
      else
        format.html { render :edit }
        format.json { render json: @upcoming_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /upcoming_events/1
  # DELETE /upcoming_events/1.json
  def destroy
    @upcoming_event.destroy
    respond_to do |format|
      format.html { redirect_to upcoming_events_url, notice: 'Upcoming event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upcoming_event
      @upcoming_event = UpcomingEvent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upcoming_event_params
      params.require(:upcoming_event).permit(:name, :content, :newsletter_id)
    end
end

app/helpers/upcoming_events_helper.rb
module UpcomingEventsHelper
end

app/views/upcoming_events/_form.html.erb
<%= form_for(@upcoming_event) do |f| %>
  <% if @upcoming_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upcoming_event.errors.count, "error") %> prohibited this upcoming_event from being saved:</h2>

      <ul>
      <% @upcoming_event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :newsletter_id %><br>
    <%= f.number_field :newsletter_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/upcoming_events/edit.html.erb
<h1>Editing upcoming_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @upcoming_event %> |
<%= link_to 'Back', upcoming_events_path %>

app/views/upcoming_events/index.html.erb
<h1>Listing upcoming_events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
      <th>Newsletter</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @upcoming_events.each do |upcoming_event| %>
      <tr>
        <td><%= upcoming_event.name %></td>
        <td><%= upcoming_event.content %></td>
        <td><%= upcoming_event.newsletter_id %></td>
        <td><%= link_to 'Show', upcoming_event %></td>
        <td><%= link_to 'Edit', edit_upcoming_event_path(upcoming_event) %></td>
        <td><%= link_to 'Destroy', upcoming_event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Upcoming event', new_upcoming_event_path %>

app/views/upcoming_events/new.html.erb
<h1>New upcoming_event</h1>

<%= render 'form' %>

<%= link_to 'Back', upcoming_events_path %>

app/views/upcoming_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @upcoming_event.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @upcoming_event.content %>
</p>

<p>
  <strong>Newsletter:</strong>
  <%= @upcoming_event.newsletter_id %>
</p>

<%= link_to 'Edit', edit_upcoming_event_path(@upcoming_event) %> |
<%= link_to 'Back', upcoming_events_path %>